# Generated by Django 3.2.8 on 2022-09-04 03:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_shorturl_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorturl',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 4, 3, 34, 14, 457536, tzinfo=utc)),
        ),
    ]
