# Generated by Django 3.2.8 on 2022-09-04 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_shorturl_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorturl',
            name='created_at',
            field=models.DateTimeField(verbose_name='created_at'),
        ),
    ]
