# Generated by Django 3.2.8 on 2022-09-04 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_shorturl_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorturl',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
